# Lab 1: Practice Working with NumPy and Pandas

In [1]:
import pandas as pd
import numpy as np

In this lab you will practice working with the NumPy and Pandas packages. You will:

1. Work with NumPy arrays and NumPy functions.
2. Create Pandas DataFrames from data
3. Use NumPy and Pandas to analyze the data
4. Visualize the data with Matplotlib

## Part 1. NumPy Arrays

### a. Define a new Python *list*

Let us practice defining a new list in Python:

In [2]:
my_list = [0,0,1,2,3,3,4.5,7.6]
my_list

[0, 0, 1, 2, 3, 3, 4.5, 7.6]

### b. (Two ways to) define a *range*

One type of list is a range of (e.g., integer) numbers. Ranges are useful for iterating over in a loop -- that is, to assign some variable to take on each value in this list sequentially. (For example, `i=1`, then `i=2`, then `i=3`, etc., until `i=100`.) <br>

Let's create an evenly spaced array of integers ranging from 0 to 11:

In [3]:
#First, the basic python way:
my_range = range(0,12)
my_range

range(0, 12)

In [4]:
#Now the numpy way:
my_range_np = np.arange(12)
my_range_np

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

You can see that the first method returns a special 'range' object, while the latter returns an object of type 'numpy array'. If we convert both to lists, they will be the same:

In [5]:
list(my_range)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [6]:
list(my_range_np)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

### c. List comprehension

Consider the task of replacing each value in a list with its square. The traditional way of performing te same transformation on every element of a list is via a `for` loop:

In [7]:
my_range_np = np.arange(12)

for i in range(0, len(my_range_np)):
    my_range_np[i] = my_range_np[i]**2 #square each element
print(my_range_np)

[  0   1   4   9  16  25  36  49  64  81 100 121]


That worked. However, there is a better, more 'Pythonic' way to do it. <br>

*List comprehension* is one of the most elegant functionalities native to Python, and is beloved by programmers like you. It offers a concise way of applying a particular transformation to every element in a list. <br>

Using list comprehension syntax, we can write a single, easily interpretable line that does the same transformation without using ranges, nor do we have to introduce an iterating index variable `i`:

In [8]:
my_range_np = np.arange(12)

my_range_np = [x**2 for x in my_range_np]
my_range_np

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121]

### d. Creating a one-dimensional NumPy *array*. 

Let's explicitly create a one-dimensional `numpy` array (as opposed to a list):

In [9]:
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

### e.  Retrieving the dimensions of data structure:  len() and np.shape()

How would we go about creating a variable that contains the length of our array `arr` ?<br>
We could use the Python function ```len()```... 

In [10]:
arr_length = len(arr)
arr_length

4

... or use the `numpy` function ```np.shape()```, saving only the first of the two values that it returns:

In [14]:
arr_length = np.shape(arr)
arr_length

(4,)

<b>Tip</b>: try removing the slice indicator `[0]` and see how the output changes. Notice that there appears to be an empty 'slot' for another number in the returned value pair.

### f. Creating a uniform (same value in every position) array: np.ones()

We will now use ```np.ones()``` to create an array of a pre-specified length that contains the value '1' in each position:

In [15]:
length = 55
np.ones(length, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

We can use this method to create an array of any identical values. <br>
Let's create an array of length 13, filled with the vlue '7' in every position:

In [16]:
7*np.ones(13, dtype=int)

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])

### g. Creating two-dimensional arrays

Exploring the possibilities of the ```np.array()``` function further, let's move on to creating not one- but two-dimensional arrays (aka matrices):

In [17]:
M = np.array([[1,2,3], [4,5,6]])
M

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
np.shape(M)

(2, 3)

NumPy contains useful functions for creating identity matrices of a specified size:

### h. Creating an identity matrix: np.eye()

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
#check your intuition: what will be the output after running this cell?
A = np.eye(3)
B = 4*np.eye(3)
A+B

array([[5., 0., 0.],
       [0., 5., 0.],
       [0., 0., 5.]])

### i. A small challenge:  matrix transformation and random matrix generation
Using the matrix ```M``` below and the function ```np.triu()```. Inspect the documentation by running the command ```np.triu?``` in the cell below. Create a matrix ```N``` which is identical to ```M``` except in the lower triangle (i.e., all the cells below the diagonal). The lower triangle should be filled with zeros.

In [21]:
np.triu?

In [26]:
M = np.round(np.random.rand(5,5),2)
print("M=\n", M)

# your code here:
N = np.triu(M)
print("N=\n",N)

M=
 [[0.67 0.17 0.24 0.71 0.36]
 [0.32 0.36 0.77 0.3  0.4 ]
 [0.01 0.85 0.81 0.54 0.1 ]
 [0.85 0.14 0.49 0.7  0.78]
 [0.65 0.54 0.81 0.17 0.23]]
N=
 [[0.67 0.17 0.24 0.71 0.36]
 [0.   0.36 0.77 0.3  0.4 ]
 [0.   0.   0.81 0.54 0.1 ]
 [0.   0.   0.   0.7  0.78]
 [0.   0.   0.   0.   0.23]]


Using the code provided above for generating the matrix ```M```, try to figure out how to create a random matrix with 13 rows and 3 columns. <br>

In [27]:
# your code here:
M = np.random.rand(13,3)
print("M=\n",M)


M=
 [[0.17612676 0.80649644 0.96702546]
 [0.93896479 0.17882376 0.73688463]
 [0.07709615 0.440969   0.1962623 ]
 [0.06703329 0.38333823 0.93442992]
 [0.75016411 0.70184773 0.14258908]
 [0.29956625 0.08804708 0.83295163]
 [0.6290715  0.63678086 0.71965698]
 [0.74085597 0.34385167 0.93587761]
 [0.83495483 0.0274031  0.8277402 ]
 [0.23743072 0.25422158 0.58413473]
 [0.11065284 0.38671493 0.62860077]
 [0.27594726 0.83470893 0.17549189]
 [0.71856689 0.52837288 0.46693125]]


### j. Indexing and slicing arrays

Here is how to call an element of a 2D array by its location (i.e., its row index and column index):

In [28]:
M[3,2]

0.9344299193321595

In [29]:
# test your intuition: what would you expect this code to return?
M[3:,2]

array([0.93442992, 0.14258908, 0.83295163, 0.71965698, 0.93587761,
       0.8277402 , 0.58413473, 0.62860077, 0.17549189, 0.46693125])

### k. Evaluating a Boolean condition

In real-life data tasks, you will often have to compute the boolean ```(True/False)``` value of some statement, for all entries in a list, or for a matrix column (essentially, a list), or for the entire matrix. <br>
In other words, we may want to formulate a condition -- think of it as a *test* -- and run a computation that returns `True` or `False` depending on whether the test is passed or failed by a particular value in a data structure.

For example, our test may be something like "the value is greater than 0.5", and we would like to know if this is true or false for each of the values in a list. Here's how to compute a list of values that the condition test takes for each value of a given list:

In [30]:
g = np.random.rand(1, 20) #first, create the list 
print(g)

[[0.3413255  0.98790183 0.68834594 0.73846421 0.52793396 0.69450383
  0.88598525 0.06107866 0.07554916 0.65135315 0.54289112 0.78216869
  0.5447637  0.40631568 0.89802768 0.9651375  0.97839161 0.4042257
  0.42663733 0.8993635 ]]


In [31]:
is_greater = g>0.5
print(is_greater)

[[False  True  True  True  True  True  True False False  True  True  True
   True False  True  True  True False False  True]]


In [32]:
# Let's print the matrix M again so we can glance at it for our next exercise
print(M)

[[0.17612676 0.80649644 0.96702546]
 [0.93896479 0.17882376 0.73688463]
 [0.07709615 0.440969   0.1962623 ]
 [0.06703329 0.38333823 0.93442992]
 [0.75016411 0.70184773 0.14258908]
 [0.29956625 0.08804708 0.83295163]
 [0.6290715  0.63678086 0.71965698]
 [0.74085597 0.34385167 0.93587761]
 [0.83495483 0.0274031  0.8277402 ]
 [0.23743072 0.25422158 0.58413473]
 [0.11065284 0.38671493 0.62860077]
 [0.27594726 0.83470893 0.17549189]
 [0.71856689 0.52837288 0.46693125]]


In [33]:
# What would you expect to see once you run the code below?
c_is_greater = M[:,1]>0.5
c_is_greater

array([ True, False, False, False,  True, False,  True, False, False,
       False, False,  True,  True])

### L . NumPy Functions `np.any()`, `np.unique() `

We can use ```np.any()``` to determine if there is any entry in column 1 that is smaller than 0.1:

In [34]:
c_is_smaller = M[:,1]<0.1
np.any(c_is_smaller)

True

A small challenge:<br>
You have birthday data for a cohort of 100 people all born in 1990.
Given the one-dimensional array of birthdays ```random_bdays``` generated below, figure out if there exists a pair of people who share a birthday.<br>

<b>Tip</b>: you may find the function ```np.unique()``` useful. Feel free to read up on it by running the command `np.unique?` in a new cell.

In [44]:
# do not edit this code:
random_nums = np.random.choice(365, size = 100)
random_bdays = np.datetime64('1990-01-01') + random_nums

## your code here:
u, c = np.unique(random_bdays, return_counts=True)
duplicates_exist = u[c > 1]
print(duplicates_exist)

['1990-01-09' '1990-01-31' '1990-02-03' '1990-03-18' '1990-06-30'
 '1990-07-30' '1990-08-14' '1990-08-26' '1990-09-08' '1990-10-17'
 '1990-10-28' '1990-11-03' '1990-11-10' '1990-12-14']


## Part 2. Pandas DataFrames

### a. Creating a DataFrame: two (of the many) ways

The code cells below demonstrate how we can create Pandas DataFrames from scratch: from a *list of lists*, and from a *dictionary*. First, the cell below creates a DataFrame from a list containing phone numbers and their country codes. The DataFrame is named `df`. Run the cell below to inspect the DataFrame `df` that was created.

In [45]:
my_list = [['+1', '(929)-000-0000'], ['+34', '(917)-000-0000'], ['+7', '(470)-000-0000']]
df = pd.DataFrame(my_list, columns = ['country_code', 'phone'])
df

country_code           phone
0           +1  (929)-000-0000
1          +34  (917)-000-0000
2           +7  (470)-000-0000

Second, the cell below creates a DataFrame from a dictionary that contains the same information as the list above. The dictionary contains phone numbers and their country codes. Run the cell below to inspect the DataFrame `df_from_dict` that was created from the dictionary. Notice that both DataFrames `df` and `df_from_dict` contain the same values.

In [46]:
my_dict = {'country_code': ['+1', '+34', '+7'], 'phone':['(929)-000-0000', '(917)-000-0000', '(470)-000-0000']}
df_from_dict = pd.DataFrame(my_dict)
df_from_dict

country_code           phone
0           +1  (929)-000-0000
1          +34  (917)-000-0000
2           +7  (470)-000-0000

### b. Adding a column to a DataFrame object

We are going to continue working with the DataFrame `df` that was created above. In the code cell below, we add a new column of values to DataFrame `df`. Run the cell and inspect the DataFrame to see the new column that was added.

In [47]:
df['grade']= ['A','B','A']
df

country_code           phone grade
0           +1  (929)-000-0000     A
1          +34  (917)-000-0000     B
2           +7  (470)-000-0000     A

### c. Sorting the DataFrame by values in a specific column: `df.sort_values()`

In [48]:
df = df.sort_values(['grade'])
df

country_code           phone grade
0           +1  (929)-000-0000     A
2           +7  (470)-000-0000     A
1          +34  (917)-000-0000     B

### d. Combining multiple DataFrames with `pd.concat()` and `pd.merge()` and renaming  columns with `df.rename()`

In real life settings, you will often need to combine separate sets of related data.<br>
To illustrate, let's create a new DataFrame. The code cell below creates a new DataFrame `df2` that also contains phone numbers, their country codes and a grade. Run the cell and inspect the new DataFrame that was created.

In [49]:
my_dict2 = {'country': ['+32', '+81', '+11'], 'grade':['B', 'B+', 'A'], 'phone':['(874)-444-0000', '(313)-003-1000', '(990)-006-0660']}
df2 = pd.DataFrame(my_dict2)
df2

country grade           phone
0     +32     B  (874)-444-0000
1     +81    B+  (313)-003-1000
2     +11     A  (990)-006-0660

The code cell below uses the Pandas ```pd.concat()``` function to append the second DataFrame to the first one. It saves the newly formed DataFrame to variable `df_concat`. Note that the `pd.concat()` function will not change the values in the original DataFrames.

In [50]:
df_concat = pd.concat([df,df2])
df_concat

country_code           phone grade country
0           +1  (929)-000-0000     A     NaN
2           +7  (470)-000-0000     A     NaN
1          +34  (917)-000-0000     B     NaN
0          NaN  (874)-444-0000     B     +32
1          NaN  (313)-003-1000    B+     +81
2          NaN  (990)-006-0660     A     +11

Notice that the new DataFrame contains redundancy caused by the different spelling of the column names that contain the country code in the two original DataFrames. This can be easily fixed. The code cell below changes the name of the column in DataFrame `df2` to be consistent with the name of the column in DataFrame `df`.

In [51]:
df2 = df2.rename(columns={'country':'country_code'})
df2

country_code grade           phone
0          +32     B  (874)-444-0000
1          +81    B+  (313)-003-1000
2          +11     A  (990)-006-0660

<b>Task</b>: In the cell below, run the `pd.concat()` function again to concatenate DataFrames `df` and `df2` and save the resulting DataFrame to variable `df_concat`. Run the cell and inpect the results.

In [52]:
df_concat = pd.concat([df,df2])
df_concat

country_code           phone grade
0           +1  (929)-000-0000     A
2           +7  (470)-000-0000     A
1          +34  (917)-000-0000     B
0          +32  (874)-444-0000     B
1          +81  (313)-003-1000    B+
2          +11  (990)-006-0660     A

One other problem is that the index has repeated values. This defeats the purpose of an index, and ought to be fixed. Let's try the concatenation again, this time adding `reset_index()` method to produce correct results:

In [53]:
df_concat = pd.concat([df,df2]).reset_index()
df_concat

index country_code           phone grade
0      0           +1  (929)-000-0000     A
1      2           +7  (470)-000-0000     A
2      1          +34  (917)-000-0000     B
3      0          +32  (874)-444-0000     B
4      1          +81  (313)-003-1000    B+
5      2          +11  (990)-006-0660     A

What if our task was to merge ```df2``` with yet another dataset -- one that contains additional unique columns? Let's look at DataFrame `df2` again:

In [54]:
df2

country_code grade           phone
0          +32     B  (874)-444-0000
1          +81    B+  (313)-003-1000
2          +11     A  (990)-006-0660

The code cell below creates a new DataFrame `df3`.

In [55]:
my_dict3 = {'country_code': ['+32', '+44', '+11'], 'phone':['(874)-444-0000', '(575)-755-1000', '(990)-006-0660'], 'grade':['B', 'B+', 'A'], 'n_credits': [12, 3, 9]}
df3 = pd.DataFrame(my_dict3)
df3

country_code           phone grade  n_credits
0          +32  (874)-444-0000     B         12
1          +44  (575)-755-1000    B+          3
2          +11  (990)-006-0660     A          9

The next cell merges both DataFrames and applies the change to DataFrame `df2`. Feel free to consult the definition of the Pandas ```merge()``` method to better undertsand how `merge()` works.

In [56]:
df2 = df2.merge(df3, on = 'phone')
df2

country_code_x grade_x           phone country_code_y grade_y  n_credits
0            +32       B  (874)-444-0000            +32       B         12
1            +11       A  (990)-006-0660            +11       A          9

### e. Loading a dataset: `pd.read_csv()`

We are now well equipped to deal with a real dataset!<br>


For the next few exercises, our dataset will contain information about New York City listings on the Airbnb platform. Note: the cell below may generate a warning. Ignore the warning. 

In [57]:
import os 
filename = os.path.join(os.getcwd(), "labs_data", "airbnb_lab1.csv.gz") # path to file and file name
data = pd.read_csv(filename)

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (56) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [58]:
data.shape

(38277, 63)

First, get a peek at the data:

In [59]:
data.head()

id       scrape_id last_scraped  host_id  host_since  host_response_time  \
0  2595  20211204143024   2021-12-05     2845  2008-09-09        within a day   
1  3831  20211204143024   2021-12-05     4869  2008-12-07  a few days or more   
2  5121  20211204143024   2021-12-05     7356  2009-02-03      within an hour   
3  5136  20211204143024   2021-12-05     7378  2009-02-03        within a day   
4  5178  20211204143024   2021-12-05     8967  2009-03-03        within a day   

  host_response_rate host_acceptance_rate host_is_superhost  \
0                80%                  17%                 f   
1                 9%                  69%                 f   
2               100%                 100%                 f   
3               100%                  25%                 f   
4               100%                 100%                 f   

   host_neighbourhood  ...  review_scores_communication  \
0             Midtown  ...                         4.79   
1        Clinton Hill  ...                         4.80   
2  Bedford-Stuyvesant  ...                         4.91   
3   Greenwood Heights  ...                         5.00   
4      Hell's Kitchen  ...                         4.42   

   review_scores_location review_scores_value license instant_bookable  \
0                    4.86                4.41     NaN                f   
1                    4.71                4.64     NaN                f   
2                    4.47                4.52     NaN                f   
3                    4.50                5.00     NaN                f   
4                    4.87                4.36     NaN                f   

  calculated_host_listings_count calculated_host_listings_count_entire_homes  \
0                              3                                           3   
1                              1                                           1   
2                              2                                           0   
3                              1                                           1   
4                              1                                           0   

  calculated_host_listings_count_private_rooms  \
0                                            0   
1                                            0   
2                                            2   
3                                            0   
4                                            1   

   calculated_host_listings_count_shared_rooms  reviews_per_month  
0                                            0               0.33  
1                                            0               4.86  
2                                            0               0.52  
3                                            0               0.02  
4                                            0               3.68  

[5 rows x 63 columns]

That's a lot of columns, and the layout is a little difficult to read. <br>
Let us retrieve just the list of column names, so we can read it and get a feeling for what kind of information is presented in the dataset.

### f. Get column names: `df.columns`

In [60]:
list(data.columns)

['id',
 'scrape_id',
 'last_scraped',
 'host_id',
 'host_since',
 'host_response_time',
 'host_response_rate',
 'host_acceptance_rate',
 'host_is_superhost',
 'host_neighbourhood',
 'host_listings_count',
 'host_total_listings_count',
 'host_verifications',
 'host_has_profile_pic',
 'host_identity_verified',
 'neighbourhood',
 'neighbourhood_cleansed',
 'neighbourhood_group_cleansed',
 'latitude',
 'longitude',
 'property_type',
 'room_type',
 'accommodates',
 'bathrooms',
 'bathrooms_text',
 'bedrooms',
 'beds',
 'amenities',
 'price',
 'minimum_nights',
 'maximum_nights',
 'minimum_minimum_nights',
 'maximum_minimum_nights',
 'minimum_maximum_nights',
 'maximum_maximum_nights',
 'minimum_nights_avg_ntm',
 'maximum_nights_avg_ntm',
 'calendar_updated',
 'has_availability',
 'availability_30',
 'availability_60',
 'availability_90',
 'availability_365',
 'calendar_last_scraped',
 'number_of_reviews',
 'number_of_reviews_ltm',
 'number_of_reviews_l30d',
 'first_review',
 'last_review',


What do the column names mean? Some of them are less intuitively interpretable than others. <br>
Careful data documentation is indispensable for business analytics. You can consult the documentation that accompanies this open source dataset for a detailed description of the key variable names, what they represent, and how they were generated.

### g. Summary statistics of the DataFrame: `df.describe()`

Let's print some general statistics for each one of the `data` columns:

In [61]:
data.describe(include='all')

id     scrape_id last_scraped       host_id  host_since  \
count   3.827700e+04  3.827700e+04        38277  3.827700e+04       38243   
unique           NaN           NaN            2           NaN        4289   
top              NaN           NaN   2021-12-05           NaN  2019-10-29   
freq             NaN           NaN        31879           NaN         433   
mean    2.962239e+07  2.021120e+13          NaN  1.148305e+08         NaN   
std     1.742239e+07  0.000000e+00          NaN  1.299194e+08         NaN   
min     2.595000e+03  2.021120e+13          NaN  2.438000e+03         NaN   
25%     1.341048e+07  2.021120e+13          NaN  1.139462e+07         NaN   
50%     3.081269e+07  2.021120e+13          NaN  5.005297e+07         NaN   
75%     4.642855e+07  2.021120e+13          NaN  2.002395e+08         NaN   
max     5.366510e+07  2.021120e+13          NaN  4.344080e+08         NaN   

       host_response_time host_response_rate host_acceptance_rate  \
count               21084              21084                21791   
unique                  4                 88                  101   
top        within an hour               100%                 100%   
freq                11151              13299                 5342   
mean                  NaN                NaN                  NaN   
std                   NaN                NaN                  NaN   
min                   NaN                NaN                  NaN   
25%                   NaN                NaN                  NaN   
50%                   NaN                NaN                  NaN   
75%                   NaN                NaN                  NaN   
max                   NaN                NaN                  NaN   

       host_is_superhost  host_neighbourhood  ...  \
count              38243               30813  ...   
unique                 2                 484  ...   
top                    f  Bedford-Stuyvesant  ...   
freq               30865                2138  ...   
mean                 NaN                 NaN  ...   
std                  NaN                 NaN  ...   
min                  NaN                 NaN  ...   
25%                  NaN                 NaN  ...   
50%                  NaN                 NaN  ...   
75%                  NaN                 NaN  ...   
max                  NaN                 NaN  ...   

        review_scores_communication  review_scores_location  \
count                  28165.000000            28151.000000   
unique                          NaN                     NaN   
top                             NaN                     NaN   
freq                            NaN                     NaN   
mean                       4.807454                4.750307   
std                        0.465544                0.416101   
min                        0.000000                0.000000   
25%                        4.810000                4.670000   
50%                        4.970000                4.880000   
75%                        5.000000                5.000000   
max                        5.000000                5.000000   

       review_scores_value   license instant_bookable  \
count         28150.000000         1            38277   
unique                 NaN         1                2   
top                    NaN  41662/AL                f   
freq                   NaN         1            27851   
mean              4.646892       NaN              NaN   
std               0.518905       NaN              NaN   
min               0.000000       NaN              NaN   
25%               4.550000       NaN              NaN   
50%               4.780000       NaN              NaN   
75%               5.000000       NaN              NaN   
max               5.000000       NaN              NaN   

       calculated_host_listings_count  \
count                    38277.000000   
unique                            NaN   
top                               NaN   
freq                 


<br>Consider the following business question:<br>
What is the average availability (out of 365 days in a year) for the listings in Brooklyn? <br>
The answer can be obtained by the use of **filters** on the dataset.

### h. Filtering the data: `df[ < condition > ]`

We need to filter the entries that are in Brooklyn. To do this, we need to know what is the exact way that Manhattan listings are spelled and entered in the data. Let's print all of the unique values of the 'neighborhood' column:

In [62]:
data['neighbourhood'].unique()

array(['New York, United States', 'Brooklyn, New York, United States',
       nan, 'Queens, New York, United States',
       'Long Island City, New York, United States',
       'Astoria, New York, United States',
       'Bronx, New York, United States',
       'Staten Island, New York, United States',
       'Elmhurst, New York, United States',
       'Riverdale , New York, United States',
       'Briarwood, New York, United States',
       'Kips Bay, New York, United States',
       'Jackson Heights, New York, United States',
       'New York, Manhattan, United States',
       'Park Slope, Brooklyn, New York, United States',
       'Kew Gardens, New York, United States',
       'Flushing, New York, United States',
       'Astoria , New York, United States',
       'Sunnyside, New York, United States',
       'Woodside, New York, United States',
       'NY , New York, United States',
       'Bushwick, Brooklyn, New York, United States',
       'Brooklyn , New York, United States', 'Uni

You may have noticed that there is a lot of heterogeneity in the way `neighborhood` values are specified. The values are not standardized. There are overlaps, redundancies, and inconsistencies (e.g., some entries specify ```'Greenpoint, Brooklyn, New York, United States'```, some other ones list `'BROOKLYN, New York, United States',`, yet other ones say `'Williamsburg, Brooklyn, New York, United States'`, etc. In real life, you would have to clean this data and replace these values with standard, identically formated, consistent values. <br>

For this data file, however, we are lucky to already have a 'cleansed' version of the neighborhood information based on the latitude and the longitude of every listing location. 

We will list the unique values of the columns titled `neighbourhood_cleansed` and `neighbourhood_group_cleansed`:

In [63]:
data['neighbourhood_cleansed'].unique()

array(['Midtown', 'Bedford-Stuyvesant', 'Sunset Park', 'Upper West Side',
       'South Slope', 'Williamsburg', 'East Harlem', 'Fort Greene',
       "Hell's Kitchen", 'East Village', 'Harlem', 'Flatbush',
       'Long Island City', 'Jamaica', 'Greenpoint', 'Nolita', 'Chelsea',
       'Upper East Side', 'Prospect Heights', 'Clinton Hill',
       'Washington Heights', 'Kips Bay', 'Bushwick', 'Carroll Gardens',
       'West Village', 'Park Slope', 'Prospect-Lefferts Gardens',
       'Lower East Side', 'East Flatbush', 'Boerum Hill', 'Sunnyside',
       'St. George', 'Tribeca', 'Highbridge', 'Ridgewood', 'Mott Haven',
       'Morningside Heights', 'Gowanus', 'Ditmars Steinway',
       'Middle Village', 'Brooklyn Heights', 'Flatiron District',
       'Windsor Terrace', 'Chinatown', 'Greenwich Village',
       'Clason Point', 'Crown Heights', 'Astoria', 'Kingsbridge',
       'Forest Hills', 'Murray Hill', 'University Heights', 'Gravesend',
       'Allerton', 'East New York', 'Stuyvesant Town

In [64]:
data['neighbourhood_group_cleansed'].unique()

array(['Manhattan', 'Brooklyn', 'Queens', 'Staten Island', 'Bronx'],
      dtype=object)

Great, this last one is what we want! Let's filter out all data entries that pertain to Brooklyn listings:

In [65]:
bk = data[data['neighbourhood_group_cleansed'] == 'Brooklyn']
bk.shape

(14716, 63)

<b>Tip</b>: to better understand what happened above, you are encouraged to insert a new code cell below and copy *just the condition* of the filter that we used on the `data` object above: `data['neighbourhood_group_cleansed'] == 'Brooklyn'`. Run the new cell and see what that condition alone evaluates to. You should see a Pandas series containing True/False values. When we use that series as a Boolean filter by writing `data[ < our Boolean series > ]`, i.e `data['neighbourhood_group_cleansed'] == 'Brooklyn']` , we are telling Pandas to keep the values in the DataFrame `data` only with those indices for which the condition evaluated to `True`. 

### i. Combining values in a column: `np.mean()`

Now that we isolated only the relevant entries, it remains to average the value of a particular column that we care about:

In [66]:
np.mean(bk['availability_365'])

118.7693666757271

### j. Group data by (categorical) column values: `df.groupby()`

The next question of interest could be:<br>
What are the top 5 most reviewed neighborhoods in New York? (By sheer number of reviews, regardless of their quality). <br>
We will use the ```groupby``` method from the Pandas package:

In [67]:
nbhd_reviews = data.groupby('neighbourhood_cleansed')['number_of_reviews'].sum()
nbhd_reviews.head()

neighbourhood_cleansed
Allerton          1611
Arden Heights       86
Arrochar           867
Arverne           3091
Astoria          18207
Name: number_of_reviews, dtype: int64

Perform a (descending order) sorting on this series:

In [68]:
nbhd_reviews = nbhd_reviews.sort_values(ascending = False)
nbhd_reviews.head(5)

neighbourhood_cleansed
Bedford-Stuyvesant    88133
Williamsburg          55122
Harlem                54824
Bushwick              34776
Hell's Kitchen        31308
Name: number_of_reviews, dtype: int64

Success!<br>
While we re at it, what are the least reviewed neighborhoods?

In [69]:
nbhd_reviews.tail(5)

neighbourhood_cleansed
Little Neck       11
Sea Gate           9
Graniteville       5
Country Club       1
Fort Wadsworth     0
Name: number_of_reviews, dtype: int64

This result makes it apparent that our dataset is somewhat messy!

Notice we could have chained the transformations above into a single command, as in:

In [ ]:
data.groupby('neighbourhood_cleansed')['number_of_reviews'].sum().sort_values(ascending = False).head(5)

This way we don't store objects that we won't need.

### Bonus: easy histogram plotting with Matplotlib: `plt.hist()`

As a final touch, run the cell below to instantly visualize the density of (average!) values of review numbers across all neighbourhoods:

In [ ]:
%matplotlib inline
nbhd_reviews.hist()

This plot suggests that the vast majority of neighborhoods have only very few reviews, with just a handful of outliers (those ranked at the top in our previous computed cell) having the number of reviews upward of 40000. 